### PR TITLE
Patch/stop copying htaccess to webinf

### PR DESCRIPTION
**Pull request by mgmathus**

### CODE REVIEW

**Comment by bdw429s** [comment]
@mgmathus Did you perform the testing that was requested in the ticket?

**Comment by mgmathus** [comment]
I have tested, after I modified the loading of the file rewriting the method, now I need to check to listen changes

**Comment by mgmathus** [comment]
> @mgmathus Why did you reload this method? Shouldn't you be overriding `loadUrlRewriterLocal()` as I put in Slack?

I was having problems with all the privates in the class, the loadUrlRewriterLocal() is been called by loadUrlRewriter

**Comment by mgmathus** [comment]
> @mgmathus Why are you getting the filter init param again? This is already handled elsewhere in the class. You only need to replace the logic found in the original method you're overriding.

this was because the `confPathStr `is a local variable in the init method and the `confPath` was private, so the only way to access the path data that I found was getting it from the filter

**Comment by mgmathus** [comment]
> @mgmathus use the appropriate logger, not `System.out`

done

**Comment by mgmathus** [comment]
> @mgmathus Why have you hard coded value and not copied the same constructor as the original method call you are overriding?

I just copy the line 170 of this class: using the filter parameter

https://github.com/cfmlprojects/urlrewritefilter/blob/master/src/main/java/org/tuckey/web/filters/urlrewrite/UrlRewriteFilter.java

**Comment by mgmathus** [comment]
> @mgmathus What is this new variable? It's not part of the base class.

I just remove this, I was using part of the reference code from the example

**Comment by mgmathus** [comment]
> @mgmathus What is this logic for? Also, where is the `checkConf()` logic from the original method. Your method needs to be doing everything the original method does.

I just review the code again, and add the checkConf()

**Pull request merged**
