### PR TITLE
Remove System.gc() calls on server start

### PR DESCRIPTION
**Pull request by pfreitag**
Looks like this was left in for debugging, and possibly may improve server startup time.

### CODE REVIEW

**Comment by bdw429s** [comment]
@pfreitag Thanks.  I've seen this code a few times and scratched my head at why it was there.  I never had a chance to actually test if removing it caused any negative effects however.  Have you tested this change to ensure it doesn't cause issues?

**Comment by pfreitag** [comment]
Hey Brad, I didn't test this change, I just thought with the comment stating it was for testing and explicit calls to System.gc() being generally discouraged that it would make sense to remove.

**Comment by bdw429s** [comment]
That's an optimistic way to look at it :)

**Comment by pfreitag** [comment]
Fingers crossed 👍

**Pull request merged**
